objects/Iteration__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Iteration_Number__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>Iteration Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Iterations</relationshipLabel>
        <relationshipName>Iterations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Iteration</label>
    <nameField>
        <displayFormat>ITER-{000000}</displayFormat>
        <label>Iteration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iterations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Iteration_Node__c.object
<CustomObject>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Iteration__c</fullName>
        <label>Iteration</label>
        <referenceTo>Iteration__c</referenceTo>
        <relationshipLabel>Iteration Nodes</relationshipLabel>
        <relationshipName>Iteration_Nodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Node_Status__c</fullName>
        <label>Node Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Play</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Node__c</fullName>
        <label>Node</label>
        <referenceTo>Node__c</referenceTo>
        <relationshipLabel>Iterations</relationshipLabel>
        <relationshipName>Iteration_Nodes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Iteration Node</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Iteration Node Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iteration Nodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Node__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Nodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase_Angle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Phase Angle</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Nodes</relationshipLabel>
        <relationshipName>Nodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Node</label>
    <nameField>
        <label>Node Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GrapevineController.cls
public class GrapevineController
{
    private Id projectId;

    public GrapevineController()
    {
        projectId = ApexPages.currentPage().getParameters().get( 'id' );
    }

    private Project__c projectRecord
    {
        get
        {
            if ( projectRecord == null && projectId != null )
            {
                projectRecord =
                [   SELECT  Id, Name,
                            Account__r.Id, Account__r.Name
                    FROM    Project__c
                    WHERE   Id = :projectId
                ];
            }
            return projectRecord;
        }
        private set;
    }

    public String projectAsJson
    {
        get
        {
            return JSON.Serialize( projectRecord );
        }
    }

    private List<Iteration__c> iterations
    {
        get
        {
            if ( iterations == null && projectId != null )
            {
                iterations =
                [   SELECT  Id, Iteration_Number__c, Start_Date__c, End_Date__c
                    FROM    Iteration__c
                    WHERE   Project__c = :projectId
                ];
            }
            return iterations;
        }
        private set;
    }
    
    public String iterationsAsJson
    {
        get
        {
            return JSON.Serialize( iterations );
        }
    }
    
    private List<Node__c> nodes
    {
        get
        {
            if ( nodes== null && projectId != null )
            {
                nodes=
                [   SELECT  Id, Name, Description__c, Start_Date__c, End_Date__c, Phase_Angle__c, Owner__r.Name,
                    (   SELECT  Id, Information__c, Iteration__r.Iteration_Number__c, Node_Status__c
                        FROM    Iteration_Nodes__r
                    )
                    FROM    Node__c
                    WHERE   Project__c = :projectId
                ];
            }
            return nodes;
        }
        private set;
    }
    
    public String nodesAsJson
    {
        get
        {
            return JSON.Serialize( nodes );
        }
    }
}